### ISSUE TITLE
Nginx: Fix cache-related configuration

### ISSUE THREAD

**Issue by indeyets** [pepyatka/pepyatka-ansible#39]
Currently, `index.html` file is served with the following cache header: `Cache-Control: max-age=315360000`

This header should be removed. Having `Etag` there is perfectly fine and it will let users always get a modern version of this file.

The change shouldn't affect js/css files, which are nicely cached and versioned

**Comment by id** [comment]
Fixed in https://github.com/pepyatka/pepyatka-ansible/pull/40
