### ISSUE TITLE
Run pm2 in the production mode

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-ansible#4]
Right now we run pm2 pepyatka-server in the development mode (default one), however we can prepare a separate config for a production environment (`./config/environments/production.js` which is missing in the server repo) with a secure `saltSecret` and `secret` values. Then run pm2 that way: `NODE_ENV=production pm2 start index.js -i 0 --name pepyatka`

**Comment by id** [comment]
I had "-i 0" switch before but it didn't work well. Had to "pm2 kill && pm2 start index.js" to make pepaytka-server working.
We can try once again together.

**Comment by id** [comment]
Also, when using --watch pm2 restarts pepyatka on every request detecting some "changes".

**Comment by id** [comment]
Deprecated after https://github.com/pepyatka/pepyatka-ansible/pull/37
